services:
  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"

  pg-master:
    image: postgres:18-alpine
    container_name: pg-master
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: appdb
    volumes:
      - ./master/init-master.sh:/docker-entrypoint-initdb.d/init-master.sh:ro
      - ./master/pg_hba.conf:/master-pg_hba.conf:ro
      - ./volumes/master:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U admin -d appdb"]
      interval: 3s
      retries: 10

  pg-replica-1:
    image: postgres:18-alpine
    container_name: pg-replica-1
    restart: always
    environment:
      POSTGRES_PASSWORD: admin_password
    depends_on:
      - pg-master
    volumes:
      - ./replica/init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh:ro
      - ./volumes/replica1:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pg-replica-2:
    image: postgres:18-alpine
    container_name: pg-replica-2
    restart: always
    environment:
      POSTGRES_PASSWORD: admin_password
    depends_on:
      - pg-master
    volumes:
      - ./replica/init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh:ro
      - ./volumes/replica2:/var/lib/postgresql/data
    ports:
      - "5434:5432"
