services:
  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"

  pg-master:
    image: postgres:18-alpine
    container_name: pg-master
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: appdb
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=trust"
    volumes:
      - master_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    command: >
      postgres
      -c listen_addresses='*'
      -c wal_level=replica
      -c max_wal_senders=10
      -c max_replication_slots=10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10
      
  pg-replica-1:
    image: postgres:18-alpine
    container_name: pg-replica-1
    restart: always
    environment:
      - PGPASSWORD=repl_password
      - MASTER_PASSWORD=admin_password
    depends_on:
      pg-master:
        condition: service_healthy
    volumes:
      - replica1_data:/var/lib/postgresql/data
      - ./replica.sh:/usr/local/bin/replica.sh
    entrypoint: ["sh", "/usr/local/bin/replica.sh"]
    ports:
      - "5433:5432"

  pg-replica-2:
    image: postgres:18-alpine
    container_name: pg-replica-2
    restart: always
    environment:
      - PGPASSWORD=repl_password
      - MASTER_PASSWORD=admin_password
    depends_on:
      pg-master:
        condition: service_healthy
    volumes:
      - replica2_data:/var/lib/postgresql/data
      - ./replica.sh:/usr/local/bin/replica.sh
    entrypoint: ["sh", "/usr/local/bin/replica.sh"]
    ports:
      - "5434:5432"

volumes:
  master_data:
  replica1_data:
  replica2_data: